### ISSUE TITLE
[CRASH] `DiscordAPIError: Missing Permissions`

### ISSUE THREAD

**Issue by MotorTruck1221** [luphoria/graim#1]
**To Reproduce**
1. Fire up the bot
2. Then on Disocrd/Matrix type ;mute @ UserExample (must be an admin)
3. See error

**Logs**
```
/home/tuckerj/Documents/graim/node_modules/discord.js/src/rest/RequestHandler.js:350
throw new DiscordAPIError(data, res.status, request);
^

DiscordAPIError: Missing Permissions
at RequestHandler.execute (/home/tuckerj/Documents/graim/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async RequestHandler.push (/home/tuckerj/Documents/graim/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
at async GuildMemberRoleManager.add (/home/tuckerj/Documents/graim/node_modules/discord.js/src/managers/GuildMemberRoleManager.js:124:7) {
method: 'put',
path: '/guilds/968319055717085184/members/818995901791207454/roles/969439573912453120',
code: 50013,
httpStatus: 403,
requestData: { json: undefined, files: [] }
}
```
**Desktop (please complete the following information):**
 - Node.js v18.0

**Additional context**

**Comment by luphoria** [comment]
Hey - for context: is this admin you are talking about registered in the graim database, or is it just an admin in the discord (with no graim data for it)?

**Comment by luphoria** [comment]
Found the issue:
despite your graim discord user's having the Administrator role, you have it lower in the roles list than the graim role
To fix this, ensure that the graim role is higher than the muted role.

Leaving this open until I specify this in config.md, however :)

**Comment by MotorTruck1221** [comment]
> Found the issue:
> 
> despite your graim discord user's having the Administrator role, you have it lower in the roles list than the graim role
> 
> To fix this, ensure that the graim role is higher than the muted role.
> 
> 
> 
> Leaving this open until I specify this in config.md, however :)

It was trying to mute the Owner of the server (which might've been the issue) although I'm pretty sure you fixed this CRASH a while ago and I never checked.... (oops)
